x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      SESSION_COOKIE_SECURE: "on"
    labels:
      - "logging=true"
    logging: *default-logging

  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    logging: *default-logging

  # Your extra services here
  resource:
    image: semtech/mu-cl-resources:1.26.0
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    logging: *default-logging

  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    environment:
      MU_SPARQL_TIMEOUT: 600
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    logging: *default-logging

  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
      - ./config/delta:/config/
    labels:
      - "logging=true"
    logging: *default-logging

  database:
    image: semtech/sparql-parser:0.0.14
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    labels:
      - "logging=true"
    logging: *default-logging

  triplestore:
    image: redpencil/virtuoso:1.2.1
    environment:
      SPARQL_UPDATE: "true"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    labels:
      - "logging=true"
    logging: *default-logging
  frontend:
    image: lblod/frontend-local-harvester
    environment:
      EMBER_METIS_BASE_URL: "http://data.lblod.info/"
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  # Metis
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
  resource-labels-cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource-labels:backend
  resource-labels:
    image: lblod/resource-label-service:0.3.2
  make-object:
    image: lblod/ldes-make-object-service
    environment:
      LANDING_ZONE_GRAPH: "http://mu.semte.ch/graphs/ldes"
      TARGET_GRAPH: "http://mu.semte.ch/graphs/public"
  consumer:
    image: redpencil/ldes-consumer
    environment:
      # change the  environment variable below to test an other ldes endpoint
      LDES_ENDPOINT_VIEW: "https://dev.roadsigns.lblod.info/ldes-mow-register/1"
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/ldes"
      INGEST_MODE: ALL
      LDES_VERSION_OF_PATH: "http://purl.org/dc/terms/isVersionOf"
      LDES_TIMESTAMP_PATH: "http://www.w3.org/ns/prov#generatedAtTime"
      PERSIST_STATE: "true"
      LOG_SPARQL_ALL: "true"
      LOG_LEVEL: "debug"
    volumes:
        - ./data/ldes-consumer:/data
